name: C/C++ CI

on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # - name: configure
      #   run: ./configure
      # - name: make
      #   run: make
      # - name: make check
      #   run: make check
      # - name: make distcheck
      #   run: make distcheck
      - name: Install g++
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-8

      - name: Build .out file
        run: make
